spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tweets
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

